// Demo data source, enabled with VITE_DEMO=1 (see data.ts). Serves one real
// part (from data/raw, regenerated by scripts in the repo history) with
// synthetic price history, so the UI can be developed without a Firebase
// project.
import type { HistoryPoint, IndexPoint, Part, Status } from './data';
import demoPartJson from './demo-part.json';

const demoPart = demoPartJson as Part;

export function getDemoPart(code: string): Part | null {
  return code === demoPart.code ? demoPart : null;
}

export function getDemoHistory(code: string): HistoryPoint[] {
  if (code !== demoPart.code) return [];
  const points: HistoryPoint[] = [];
  const end = new Date('2026-07-14T00:00:00Z').getTime();
  let price = demoPart.prices[0]?.price ?? 0.01;
  let stock = demoPart.stock;
  // Deterministic random walk with occasional repricing steps.
  let seed = 42;
  const rand = () => ((seed = (seed * 1103515245 + 12345) % 2 ** 31) / 2 ** 31);
  for (let i = 480; i >= 0; i--) {
    if (rand() < 0.04) price = Math.max(0.001, price * (0.85 + rand() * 0.3));
    stock = Math.max(0, Math.round(stock * (0.97 + rand() * 0.06)));
    points.push({
      d: new Date(end - i * 86_400_000).toISOString().slice(0, 10),
      p: Number(price.toFixed(4)),
      s: stock,
    });
  }
  return points;
}

export function getDemoStatus(): Status {
  return { date: '2026-07-14', partCount: 1586 };
}

export function getDemoIndexSeries(): IndexPoint[] {
  const points: IndexPoint[] = [];
  const end = new Date('2026-07-14T00:00:00Z').getTime();
  let index = 100;
  let seed = 7;
  const rand = () => ((seed = (seed * 1103515245 + 12345) % 2 ** 31) / 2 ** 31);
  for (let i = 480; i >= 0; i--) {
    index *= 1 + (rand() - 0.5) * 0.004;
    points.push({
      d: new Date(end - i * 86_400_000).toISOString().slice(0, 10),
      i: Number(index.toFixed(3)),
      m: Number((0.0234 * (index / 100)).toFixed(6)),
      n: 1586,
      s: Math.round(800_000_000 * (0.9 + rand() * 0.2)),
    });
  }
  return points;
}
